[package]
name = "fastlink"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
actix-web = "3.3.2"
actix-cors = "0.5.4"
dotenv = "0.15.0"
